# Generated by Django 6.0 on 2026-01-07 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField(choices=[(1, 'Département Océanographie'), (2, 'Département Hydrobiologie'), (3, 'Département Géologie-Environnement'), (4, 'Département des Énergies et de la Transition Énergétique'), (5, 'Département des Matériaux Locaux de Construction et Produits Finis')], unique=True)),
                ('description', models.TextField()),
                ('mission', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='departments/')),
                ('head_of_department', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('bio', models.TextField(blank=True)),
                ('is_head', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.department')),
            ],
            options={
                'verbose_name': 'department member',
                'verbose_name_plural': 'department members',
                'ordering': ['-is_head', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='department_projects/')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='documents/department_projects/')),
                ('status', models.CharField(choices=[('current', 'En cours'), ('completed', 'Terminé'), ('planned', 'Planifié')], default='current', max_length=20)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.department')),
            ],
            options={
                'verbose_name': 'department project',
                'verbose_name_plural': 'department projects',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='documents/department_publications/')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='main.department')),
            ],
            options={
                'verbose_name': 'department publication',
                'verbose_name_plural': 'department publications',
                'ordering': ['-publication_date', '-date_created'],
            },
        ),
    ]
