# Generated by Django 6.0 on 2026-01-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_department_departmentmember_departmentproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone du département', max_length=20),
        ),
    ]
