# Generated by Django 6.0 on 2026-01-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_department_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'image", max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text="Description affichée sur l'image", verbose_name='description')),
                ('image', models.ImageField(help_text='Image (recommandé: 1920x600px)', upload_to='hero/', verbose_name='image')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage (0 = premier)", verbose_name='order')),
                ('is_active', models.BooleanField(default=True, help_text='Afficher cette image', verbose_name='active')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'hero image',
                'verbose_name_plural': 'hero images',
                'ordering': ['order', '-date_created'],
            },
        ),
    ]
