# Generated by Django 4.2.7 on 2026-06-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_heroimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_photo', models.ImageField(blank=True, help_text='Photo du Directeur Général (recommandé: 220x280px ou portrait)', null=True, upload_to='site/', verbose_name='Photo du Directeur')),
                ('director_name', models.CharField(blank=True, default='Pr Alpha Issaga Pallé Diallo', max_length=255, verbose_name='Nom du Directeur')),
                ('director_title', models.CharField(blank=True, default='Directeur Général', max_length=255, verbose_name='Titre du Directeur')),
                ('director_quote', models.TextField(blank=True, default='La science est le langage à travers lequel nous comprenons et préservons les océans qui bordent la Guinée. Le CEREMAC engage cette responsabilité avec rigueur, ouverture et un souci constant du bien commun.', verbose_name='Citation du Directeur')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
