# Generated by Django 4.2.7 on 2026-06-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_site_settings_sitesettings_director_photo_and_more_blocking_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_photo',
            field=models.ImageField(blank=True, help_text='Photo du chef de département (recommandé: portrait)', null=True, upload_to='departments/heads/'),
        ),
    ]
