# Generated by Django 4.2.7 on 2026-06-29 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_department_head_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-is_pinned', '-publication_date', '-date_created'], 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AddField(
            model_name='news',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='displayed_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='show_on_about',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='show_on_deliverables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='show_on_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='show_on_news_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='show_on_podcasts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='show_on_workshops',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_alignment',
            field=models.CharField(choices=[('left', 'Gauche'), ('center', 'Centre'), ('right', 'Droite')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('members', 'Membres uniquement')], default='public', max_length=20),
        ),
    ]
