# Generated by Django 4.2.7 on 2026-07-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_enhance_news_wordpress_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_content',
            field=models.TextField(blank=True, default='', help_text='Contenu principal de la page À propos (supporte HTML)', verbose_name='Contenu de la page À propos'),
        ),
    ]
