# Generated by Django 4.2.7 on 2026-07-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sitesettings_about_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_administration',
            field=models.TextField(blank=True, default='', help_text='Section Organisation Administrative (supporte HTML)', verbose_name='Organisation Administrative'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_history',
            field=models.TextField(blank=True, default='', help_text='Section Historique de la page À propos (supporte HTML)', verbose_name='Historique et Évolution'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_missions',
            field=models.TextField(blank=True, default='', help_text='Section Missions (supporte HTML)', verbose_name='Missions'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_research',
            field=models.TextField(blank=True, default='', help_text='Section Domaines de Recherche (supporte HTML)', verbose_name='Domaines de Recherche'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_scientific',
            field=models.TextField(blank=True, default='', help_text='Section Organisation Scientifique (supporte HTML)', verbose_name='Organisation Scientifique'),
        ),
    ]
