# Generated by Django 4.2.7 on 2026-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_event_faq_service_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroimage',
            options={'ordering': ['page', 'order', '-date_created'], 'verbose_name': 'hero image', 'verbose_name_plural': 'hero images'},
        ),
        migrations.AddField(
            model_name='heroimage',
            name='page',
            field=models.CharField(choices=[('home', 'Accueil'), ('news', 'Actualités'), ('projects', 'Projets'), ('publications', 'Publications'), ('partners', 'Partenaires'), ('departments', 'Départements'), ('about', 'À propos'), ('contact', 'Contact'), ('events', 'Événements'), ('services', 'Services')], default='home', help_text='Page sur laquelle afficher cette image', max_length=20, verbose_name='page'),
        ),
    ]
