# Generated by Django 4.2.7 on 2026-07-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_staticpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
