# Generated by Django 5.1.15 on 2026-08-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_faq_delete_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallForProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé'), ('upcoming', 'À venir')], default='open', max_length=20)),
                ('file_path', models.FileField(blank=True, help_text="Document de l'appel à projets", null=True, upload_to='documents/calls/')),
                ('external_link', models.URLField(blank=True, help_text='Lien externe pour postuler')),
                ('image', models.ImageField(blank=True, null=True, upload_to='calls/')),
                ('is_featured', models.BooleanField(default=False, help_text="Afficher sur la page d'accueil")),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'appel à projets',
                'verbose_name_plural': 'appels à projets',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('decree', 'Décret'), ('act', 'Acte'), ('convention', 'Convention'), ('protocol', "Protocole d'accord"), ('report', 'Rapport annuel'), ('organigramme', 'Organigramme'), ('other', 'Autre')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.FileField(upload_to='documents/institutional/')),
                ('reference', models.CharField(blank=True, help_text='Numéro de référence (ex: Décret 0134)', max_length=100)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'document institutionnel',
                'verbose_name_plural': 'documents institutionnels',
                'ordering': ['-date_issued', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255, verbose_name="Nom de l'organisation")),
                ('organization_type', models.CharField(max_length=100, verbose_name="Type d'organisation")),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Nom du contact')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('partnership_type', models.CharField(max_length=100, verbose_name='Type de partenariat souhaité')),
                ('description', models.TextField(verbose_name='Description du projet de partenariat')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='pending', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'demande de partenariat',
                'verbose_name_plural': 'demandes de partenariat',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_projects', to='main.department'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Mettre en avant sur la page d'accueil"),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude pour la carte interactive', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude pour la carte interactive', null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_publications', to='main.department'),
        ),
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('article', 'Article scientifique'), ('report', 'Rapport'), ('conference', 'Acte de conférence'), ('book', 'Ouvrage'), ('thesis', 'Thèse'), ('other', 'Autre')], default='article', max_length=20),
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('scientific_description', models.TextField(blank=True, help_text='Description scientifique détaillée')),
                ('equipment', models.TextField(blank=True, help_text='Équipements disponibles')),
                ('results', models.TextField(blank=True, help_text='Résultats marquants')),
                ('image', models.ImageField(blank=True, null=True, upload_to='laboratories/')),
                ('head_name', models.CharField(blank=True, max_length=255)),
                ('head_photo', models.ImageField(blank=True, null=True, upload_to='laboratories/heads/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='main.department')),
            ],
            options={
                'verbose_name': 'laboratoire',
                'verbose_name_plural': 'laboratoires',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LibraryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('report', 'Rapport'), ('thesis', 'Thèse'), ('article', 'Article'), ('conference', 'Acte de conférence'), ('technical', 'Document technique'), ('institutional', 'Document institutionnel'), ('other', 'Autre')], default='other', max_length=20)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('ppt', 'PPT/PPTX'), ('zip', 'ZIP'), ('other', 'Autre')], default='pdf', max_length=10)),
                ('file_path', models.FileField(upload_to='library/')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=500)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_documents', to='main.department')),
            ],
            options={
                'verbose_name': 'document bibliothèque',
                'verbose_name_plural': 'documents bibliothèque',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ScientificAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('conference', 'Conférence'), ('seminar', 'Séminaire'), ('workshop', 'Atelier'), ('defense', 'Soutenance'), ('training', 'Formation'), ('colloquium', 'Colloque'), ('other', 'Autre')], default='conference', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('speaker', models.CharField(blank=True, help_text='Intervenant(s)', max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('registration_link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='agenda/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_events', to='main.department')),
            ],
            options={
                'verbose_name': 'événement scientifique',
                'verbose_name_plural': 'événements scientifiques',
                'ordering': ['-start_date'],
            },
        ),
    ]
