# Generated by Django 5.1.15 on 2026-08-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_callforprojects_institutionaldocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Classe d'icône Bootstrap (ex: bi-clipboard-data)", max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='department_services/')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.department')),
            ],
            options={
                'verbose_name': 'service de département',
                'verbose_name_plural': 'services de département',
                'ordering': ['department', 'order', 'title'],
            },
        ),
    ]
