# Generated by Django 5.1.15 on 2026-08-20 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_departmentservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.headermenuitem', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Élément de menu header',
                'verbose_name_plural': 'Éléments du menu header',
                'ordering': ['order'],
            },
        ),
    ]
