# Generated by Django 5.1.15 on 2026-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_headermenuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headermenuitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Élément de menu header', 'verbose_name_plural': 'Éléments du menu header'},
        ),
        migrations.AddField(
            model_name='headermenuitem',
            name='icon',
            field=models.CharField(blank=True, help_text="Classe d'icône Bootstrap (ex: bi-house-door)", max_length=50, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='headermenuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Chemin (ex: /contact/) ou nom de route Django (ex: main:contact). Laisser vide pour un menu déroulant simple.', max_length=255, verbose_name='URL'),
        ),
    ]
