# Generated by Django 5.1.15 on 2026-09-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du responsable'),
        ),
        migrations.AddField(
            model_name='service',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du responsable'),
        ),
        migrations.AddField(
            model_name='service',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du responsable'),
        ),
    ]
