# Generated by Django 5.1.15 on 2026-09-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_service_manager_email_service_manager_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('technology', 'Technologie'), ('process', 'Procédé'), ('product', 'Produit'), ('service', 'Service'), ('research', 'Recherche')], default='technology', max_length=20, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('idea', 'Idée'), ('development', 'En développement'), ('prototype', 'Prototype'), ('testing', 'En test'), ('completed', 'Terminé'), ('deployed', 'Déployé')], default='idea', max_length=20, verbose_name='Statut')),
                ('image', models.ImageField(blank=True, null=True, upload_to='innovations/', verbose_name='Image')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='documents/innovations/', verbose_name='Fichier')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='innovations', to='main.department', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'innovation',
                'verbose_name_plural': 'innovations',
                'ordering': ['-is_featured', '-date_created'],
            },
        ),
    ]
